# Site Settings
title: Start Jekyll
email: gjg@tskoli.is
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://localhost:4000"
twitter_username: 
github_username:  gjg
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
